# Exit if this is a non-interactive prompt.
[[ -z $PS1 ]] && return

# Enable bash completion.
[[ -x /etc/bash_completion ]] && . /etc/bash_completion
[[ -x /etc/profile.d/bash_completion.sh ]] && . /etc/profile.d/bash_completion.sh

# Load dircolors.
[[ -x ~/.dircolors ]] && eval $(dircolors ~/.dircolors)

# Execution of a directory will change into that directory.
shopt -s autocd

# Minor errors in spelling of directories are corrected.
shopt -s cdspell

# Allow ** to be used for recursive directory expansion.
shopt -s globstar

# Treat path expansion as case-insensitive.
shopt -s nocaseglob

# Append to the history file, don't overwrite it.
shopt -s histappend

# Add user binaries in ~/bin to the path.
export PATH="$HOME/bin:$PATH"

# Set the default text editor to Vim.
export EDITOR=vim
export VISUAL=vim

# Increase the size of the bash history.
export HISTSIZE=32768
export HISTFILESIZE=${HISTSIZE}

# Omit duplicates entries in bash history.
export HISTCONTROL=ignoredups

# Set minimal prompt.
export PS1="\w \$ "

# Allow sudo to be used with other aliases.
alias sudo='sudo '

# Shortcuts for traversing up directories.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Shortcuts for listing directory contents.
alias la='ls -A'
alias ll='ls -Ahl'

# Use colored man pages.
function man {
    LESS_TERMCAP_me=$(tput sgr0) \
    LESS_TERMCAP_md=$(tput bold) \
    LESS_TERMCAP_so=$(tput smso) \
    LESS_TERMCAP_se=$(tput rmso; tput sgr0) \
    LESS_TERMCAP_us=$(tput smul) \
    LESS_TERMCAP_ue=$(tput rmul; tput sgr0) \
    command man "$@"
}

# Load local bashrc for device specific configuration.
[[ -x ~/.bashrc.local ]] && . ~/.bashrc.local

