[[ -z $PS1 ]] && return

[[ -f /etc/bash_completion ]] && source /etc/bash_completion
[[ -f /etc/profile.d/bash_completion.sh ]] && source /etc/profile.d/bash_completion.sh
[[ -f ~/.cargo/env ]] && source ~/.cargo/env
[[ -f ~/.dircolors ]] && eval "$(dircolors ~/.dircolors)"

if command -v starship &> /dev/null; then
    eval "$(starship init bash)"

    function set_window_title() {
        local regex="(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]"
        local title="$(starship module directory)"
        local stripped_title="$(echo -n "$title" | sed -E "s/$regex//g")"
        echo -ne "\e]0;$stripped_title\a"
    }

    starship_precmd_user_func="set_window_title"
fi

shopt -s autocd
shopt -s cdspell
shopt -s globstar
shopt -s nocaseglob
shopt -s histappend

export HISTCONTROL=ignoredups
export HISTFILESIZE=${HISTSIZE}
export HISTSIZE=32768

export EDITOR=vim
export VISUAL=vim

export PATH="$HOME/bin:$PATH"

export PS1="\w \$ "

export LESS="--raw-control-chars"
export LESS_TERMCAP_mb=$'\e[1;36m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;;31m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;35m'

alias grep='grep --color=auto'
alias ls='ls --color=auto'

alias sudo='sudo '

alias c='code'
alias g='git'
alias l='ls'
alias la='ls -A'
alias ll='ls -Ahl'
alias n='nvim'
alias v='vim'
