add_newline = false

# The format is divided into three components:
# - Prefix
# - Postfix
# - Languages

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\

$cmake\
$crystal\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$zig\

$cmd_duration\
$line_break\
$character"""

# Prefix

[directory]
read_only = '*'
read_only_style = 'bold red'
style = 'bold cyan'
truncation_length = 3
truncation_symbol = '.../'

[git_branch]
style = 'bold purple'
symbol = ''

# TODO: Fix issue where $tag has a leading space.
[git_commit]
commit_hash_length = 8
format = '[\(($tag, )$hash\)]($style) '
style = 'bold green'
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[\($state ($progress_current of $progress_total)\)]($style) '

# TODO: Understand the different git statuses.
[git_status]

[package]
style = 'bold yellow'
symbol = ''

# Postfix

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[cmd_duration]
style = 'yellow'

# Languages

[cmake]
symbol = 'cmake '

[crystal]
symbol = 'crystal '

[dart]
symbol = 'dart '

[dotnet]
format = 'via [$symbol$version( \($tfm\))]($style) '
symbol = 'dotnet '

[elixir]
symbol = 'elixir '

[elm]
symbol = 'elm '

[erlang]
symbol = 'erlang '

[golang]
symbol = 'go '

[java]
symbol = 'java '

[julia]
symbol = 'julia '

[nim]
symbol = 'nim '

[nodejs]
symbol = 'node '

[ocaml]
symbol = 'ocaml '

[perl]
symbol = 'perl '

[php]
symbol = 'php '

[purescript]
symbol = 'purescript '

[python]
symbol = 'python '

[ruby]
symbol = 'ruby '

[rust]
symbol = 'rust '

[swift]
symbol = 'swift '

[zig]
symbol = 'zig '
