set autoindent
set backspace=eol,indent,start
set belloff=all
set encoding=utf-8
set expandtab
set foldopen=mark,search,tag,undo
set hidden
set ignorecase
set incsearch
set laststatus=2
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set mouse=a
set nohlsearch
set noshowmode
set nowrap
set number
set relativenumber
set ruler
set scrolloff=4
set shiftwidth=4
set sidescrolloff=4
set smartcase
set smartindent
set softtabstop=4
set spelllang=en_au,en_gb
set splitbelow
set splitright
set tabstop=4
set wildmenu

noremap <Space> <Leader>
noremap <C-c> <Esc>
noremap j gj
noremap k gk

filetype plugin indent on
syntax on
