#   . B A S H _ P R O F I L E


# do not do anything if this is not an interactive session.
[[ -z $PS1 ]] && return

# source global configuration.
[[ -f /etc/bashrc ]] && . /etc/bashrc

# source bash completion.
# NOTE: some distributions use a profile.d script to import completion.
[[ -f /etc/bash_completion ]] && . /etc/bash_completion
[[ -f /etc/profile.d/bash_completion.sh ]] && . /etc/profile.d/bash_completion.sh

# load dircolors configuration.
[[ -f ~/.dircolors ]] && eval $(dircolors ~/.dircolors)


#   O P T I O N S

# execution of a directory, changes into the directory.
shopt -s autocd

# minor errors in the spelling of directories are corrected.
shopt -s cdspell

# allow ** to be used for recursive directory expansion.
shopt -s globstar

# path expansion is now treated as case-insensitive.
shopt -s nocaseglob

# append to the history file, don't overwrite it.
shopt -s histappend


#   E X P O R T S

# add ~/bin to the path.
export PATH=$HOME/bin:$PATH

# set the default text editor to vim.
export EDITOR=vim
export VISUAL=vim

# set the default web browser to google chrome.
export BROWSER=google-chrome

# increase the size of bash history.
export HISTSIZE=32768
export HISTFILESIZE=${HISTSIZE}

# omit duplicates entries in bash history.
export HISTCONTROL=ignoredups


#   A L I A S E S

# allow sudo to be used with other aliases.
alias sudo='sudo '

# enable colors for common utilities.
alias ls='ls --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# shorthands for traversing up directories.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# shorthands for listing directory contents.
alias la='ls -A'
alias ll='ls  -Ahl'

# replace the current bash instance with a new instance.
alias reset="exec $BASH"

# preserve the current bash instance, but resource the .bash_profile.
alias reload="source $HOME/.bash_profile"

# open a given file or folder with the default application.
# NOTE: requires xdg-open.
# TODO: create a platform independent polyfill.
alias open='xdg-open &>/dev/null'

# serve the current directory as static files.
# NOTE: requires python3.
alias serve='python3 -m http.server'


#   F U N C T I O N S

# show colour man pages by adjusting less terminal capabilities.
function man {
    LESS_TERMCAP_me=$(tput sgr0) \
    LESS_TERMCAP_md=$(tput bold) \
    LESS_TERMCAP_so=$(tput smso) \
    LESS_TERMCAP_se=$(tput rmso; tput sgr0) \
    LESS_TERMCAP_us=$(tput smul) \
    LESS_TERMCAP_ue=$(tput rmul; tput sgr0) \
    command man "$@"
}


#   P R O M P T

# e.g.
# [scott@air240] [~/code/dotfiles] [master:!?]
# [11:14:45] $
# TODO: fix git prompt.

# define prompt colours.
rst="\[$(tput sgr0)\]"
for ((i=1; i<=7; i++)); do
    declare "fg${i}"="\[$(tput setaf ${i})\]"
done

# build prompt.
function __prompt {
    local exit_code=$?
    PS1="${rst}"
    PS1+="[${fg6}\u@\h${rst}] "
    PS1+="[${fg4}\w${rst}] "
    PS1+="[${fg5}master${rst}] "
    PS1+="\n"
    if [[ "$exit_code" -eq 0 ]]; then
        PS1+="[${fg2}\t${rst}] "
    else
        PS1+="[${fg1}\t${rst}] "
    fi
    PS1+="\$ "
}

# use a prompt command to update dynamic prompt elements.
PROMPT_COMMAND="__prompt"


#   S O U R C E

# load local hook for device specific configuration.
# NOTE: this needs to be sourced at the bottom of the file.
if [ -f $HOME/.bashrc.local ]; then
    . $HOME/.bashrc.local
fi
